### ISSUE TITLE
item布局

### ISSUE THREAD

**Issue by everyline** [simplepeng/MaxLineLayoutManager#1]
当item 布局中 有很多控件的时候 怎么测量 控制显示固定的数目

**Comment by simplepeng** [comment]
@everyline 没懂你的意思

**Comment by everyline** [comment]
> @everyline 没懂你的意思

就是当item 中 有多个控件的时候  显示固定的数目 就不行了。测量出现问题， demo 中只有一个textview，所以没问题，换成多个textview 就有问题

**Comment by simplepeng** [comment]
@everyline 是的，这个LayoutManager的使用场景就是item高度一致的情况，如果有多类型item，或者item高度不一样就不适用了
